version: '3'

services:
  worker1:
    build:
        context: ./
        dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - theta_restapi
      
  worker2:
    privileged: true
    build:
        context: ./
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - theta_restapi
      
  worker3:
    privileged: true
    build:
        context: ./
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - theta_restapi
    

networks:
  theta_restapi:
