spring:
  application:
    name: thetaREST

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  servlet:
    multipart:
      max-file-size:  -1
      max-request-size: -1


  codec:
    max-in-memory-size: -1

server:
  port: 9090

logging:
  level:
    root: OFF